SELECT
JH.EMPLOYEE_ID,
(SELECT CONCAT (UCASE(E.FIRST_NAME), ' ', UCASE(E.LAST_NAME))
FROM hr.employees AS E
WHERE E.EMPLOYEE_ID = JH.EMPLOYEE_ID) AS `Nome completo`,
JH.START_DATE,
(SELECT E.SALARY
FROM hr.employees AS E
WHERE E.EMPLOYEE_ID = JH.EMPLOYEE_ID) AS `salary`
FROM hr.job_history AS JH
WHERE MONTH(JH.START_DATE) IN (1 , 2, 3)
ORDER BY `Nome completo`;
